from pathlib import Path

mocked_data_path = Path(__file__).parent / "data"

mocked_planets = {
    "0": "TestPlanet",
    "1": "Tatooine",
    "2": "Alderaan",
    "3": "Yavin IV",
    "4": "Hoth",
    "5": "Dagobah",
    "6": "Bespin",
    "7": "Endor",
    "8": "Naboo",
    "9": "Coruscant",
    "10": "Kamino",
    "11": "Geonosis",
    "12": "Utapau",
    "13": "Mustafar",
    "14": "Kashyyyk",
    "15": "Polis Massa",
    "16": "Mygeeto",
    "17": "Felucia",
    "18": "Cato Neimoidia",
    "19": "Saleucami",
    "20": "Stewjon",
    "21": "Eriadu",
    "22": "Corellia",
    "23": "Rodia",
    "24": "Nal Hutta",
    "25": "Dantooine",
    "26": "Bestine IV",
    "27": "Ord Mantell",
    "28": "unknown",
    "29": "Trandosha",
    "30": "Socorro",
    "31": "Mon Cala",
    "32": "Chandrila",
    "33": "Sullust",
    "34": "Toydaria",
    "35": "Malastare",
    "36": "Dathomir",
    "37": "Ryloth",
    "38": "Aleen Minor",
    "39": "Vulpter",
    "40": "Troiken",
    "41": "Tund",
    "42": "Haruun Kal",
    "43": "Cerea",
    "44": "Glee Anselm",
    "45": "Iridonia",
    "46": "Tholoth",
    "47": "Iktotch",
    "48": "Quermia",
    "49": "Dorin",
    "50": "Champala",
    "51": "Mirial",
    "52": "Serenno",
    "53": "Concord Dawn",
    "54": "Zolan",
    "55": "Ojom",
    "56": "Skako",
    "57": "Muunilinst",
    "58": "Shili",
    "59": "Kalee",
    "60": "Umbara",
}

mocked_people = [
    {
        "name": "Test Name",
        "height": "0000",
        "mass": "0000",
        "hair_color": "Test Hair color",
        "skin_color": "Test Skin color",
        "eye_color": "Test Eye Color",
        "birth_year": "0000",
        "gender": "Test Gender",
        "homeworld": "Test Homeworld",
        "date": "0000-00-00",
    },
    {
        "name": "Luke Skywalker",
        "height": "172",
        "mass": "77",
        "hair_color": "blond",
        "skin_color": "fair",
        "eye_color": "blue",
        "birth_year": "19BBY",
        "gender": "male",
        "homeworld": "Tatooine",
        "date": "2021-06-04",
    },
    {
        "name": "Owen Lars",
        "height": "178",
        "mass": "120",
        "hair_color": "brown, grey",
        "skin_color": "light",
        "eye_color": "blue",
        "birth_year": "52BBY",
        "gender": "male",
        "homeworld": "Tatooine",
        "date": "2021-06-04",
    },
    {
        "name": "Beru Whitesun lars",
        "height": "165",
        "mass": "75",
        "hair_color": "brown",
        "skin_color": "light",
        "eye_color": "blue",
        "birth_year": "47BBY",
        "gender": "female",
        "homeworld": "Tatooine",
        "date": "2021-06-04",
    },
]
